CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE energy_supply_gdp (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, year INTEGER NOT NULL, precentage DOUBLE PRECISION NOT NULL);
CREATE TABLE renewable_energy_percentage (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, year INTEGER NOT NULL, vim INTEGER DEFAULT NULL, el INTEGER DEFAULT NULL, transport INTEGER DEFAULT NULL, total INTEGER DEFAULT NULL);
CREATE TABLE renewable_energy_twh (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, year INTEGER NOT NULL, biofuels INTEGER DEFAULT NULL, hydropower INTEGER DEFAULT NULL, wind_power INTEGER DEFAULT NULL, heat_pump INTEGER DEFAULT NULL, solar_energy INTEGER DEFAULT NULL, total INTEGER DEFAULT NULL, stat_transfer_to_norway INTEGER DEFAULT NULL, renewable_energy_in_target_calculation INTEGER DEFAULT NULL, total_energy_use INTEGER DEFAULT NULL);
CREATE TABLE doctrine_migration_versions (version VARCHAR(191) NOT NULL, executed_at DATETIME DEFAULT NULL, execution_time INTEGER DEFAULT NULL, PRIMARY KEY(version));
CREATE TABLE product (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(255) NOT NULL, value INTEGER NOT NULL);
CREATE TABLE messenger_messages (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, body CLOB NOT NULL, headers CLOB NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL --(DC2Type:datetime_immutable)
        , available_at DATETIME NOT NULL --(DC2Type:datetime_immutable)
        , delivered_at DATETIME DEFAULT NULL --(DC2Type:datetime_immutable)
        );
CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name);
CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at);
CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at);
CREATE TABLE library (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, title VARCHAR(255) NOT NULL, isbn VARCHAR(13) NOT NULL, author VARCHAR(255) NOT NULL, cover VARCHAR(255) NOT NULL);
CREATE UNIQUE INDEX UNIQ_A18098BCCC1CF4E6 ON library (isbn);
