# config/services.yaml
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Makes classes in src/ available to be used as services
    # This creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    # Controllers are imported separately to make sure services can be injected
    # as action arguments even if you make your services lazy
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Register Excel import services
    App\ExcelImport\ImportService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    App\ExcelImport\ImportExcelCommand:
        arguments:
            $importService: '@App\ExcelImport\ImportService'
        tags:
            - { name: 'console.command' }
