services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Register custom commands and services
    App\Service\ImportService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    App\Service\ResetAndImportDataCommand:
        arguments:
            $importService: '@App\Service\ImportService'
        tags:
            - { name: 'console.command' }

   