services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Register services and commands
    App\Service\ImportService: ~

    App\Command\CalculateConsumptionPerCapitaCommand: ~
    App\Command\ImportExcelCommand: ~
    App\Command\ResetAndImportDataCommand: ~
    App\Command\CalculatePopulationCommand: ~
    App\Command\CalculateAnnualCostPerPersonCommand: ~

    # Register SpreadsheetLoader and its dependencies
    PhpOffice\PhpSpreadsheet\Reader\Xlsx: ~

    App\Service\SpreadsheetLoader:
        arguments:
            $reader: '@PhpOffice\PhpSpreadsheet\Reader\Xlsx'
